### ISSUE TITLE
Admin page for adding new collection point doesn't allow certain fields to be edited

### ISSUE THREAD

**Issue by jamestyack** [GreenSTEM-Network/GreenSTEM-Server#1]
See page:- http://solarsunflower.herokuapp.com/admin/collection_point/new

Kevin has found the following link that relates to this problem:-

http://stackoverflow.com/questions/15161759/using-rails-admin-to-display-dropdown-list-on-belongs-to-association

**Comment by titlecharacter** [comment]
Issue is OBE due to changes to the schema
