### ISSUE TITLE
"no implicit conversion of nil into String" on rake db:seed

### ISSUE THREAD

**Issue by christophernies** [GreenSTEM-Network/GreenSTEM-Server#2]
[nies@localhost Server]$ rake db:seed --trace
*\* Invoke db:seed (first_time)
*\* Execute db:seed
*\* Invoke db:abort_if_pending_migrations (first_time)
*\* Invoke environment (first_time)
*\* Invoke rails_admin:disable_initializer (first_time)
*\* Execute rails_admin:disable_initializer
[RailsAdmin] RailsAdmin initialization disabled by default. Pass SKIP_RAILS_ADMIN_INITIALIZER=false if you need it.
*\* Execute environment
*\* Invoke db:load_config (first_time)
*\* Execute db:load_config
*\* Execute db:abort_if_pending_migrations
ROLES
rake aborted!
no implicit conversion of nil into String
/home/nies/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/psych.rb:205:in `parse'
/home/nies/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/psych.rb:205:in`parse_stream'
/home/nies/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/psych.rb:153:in `parse'
/home/nies/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/psych.rb:129:in`load'
/home/nies/Documents/SolarSunflowerProject/Server/db/seeds.rb:11:in `<top (required)>'
/home/nies/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:245:in`load'
/home/nies/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:245:in `block in load'
/home/nies/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:236:in`load_dependency'
/home/nies/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-3.2.12/lib/active_support/dependencies.rb:245:in `load'
/home/nies/.rvm/gems/ruby-2.0.0-p353/gems/railties-3.2.12/lib/rails/engine.rb:520:in`load_seed'
/home/nies/.rvm/gems/ruby-2.0.0-p353/gems/activerecord-3.2.12/lib/active_record/railties/databases.rake:333:in `block (2 levels) in <top (required)>'
/home/nies/.rvm/gems/ruby-2.0.0-p353/gems/rake-10.0.3/lib/rake/task.rb:228:in`call'
/home/nies/.rvm/gems/ruby-2.0.0-p353/gems/rake-10.0.3/lib/rake/task.rb:228:in `block in execute'
/home/nies/.rvm/gems/ruby-2.0.0-p353/gems/rake-10.0.3/lib/rake/task.rb:223:in`each'
/home/nies/.rvm/gems/ruby-2.0.0-p353/gems/rake-10.0.3/lib/rake/task.rb:223:in `execute'
/home/nies/.rvm/gems/ruby-2.0.0-p353/gems/rake-10.0.3/lib/rake/task.rb:166:in`block in invoke_with_call_chain'
/home/nies/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
/home/nies/.rvm/gems/ruby-2.0.0-p353/gems/rake-10.0.3/lib/rake/task.rb:159:in`invoke_with_call_chain'
/home/nies/.rvm/gems/ruby-2.0.0-p353/gems/rake-10.0.3/lib/rake/task.rb:152:in `invoke'
/home/nies/.rvm/gems/ruby-2.0.0-p353/gems/rake-10.0.3/lib/rake/application.rb:143:in`invoke_task'
/home/nies/.rvm/gems/ruby-2.0.0-p353/gems/rake-10.0.3/lib/rake/application.rb:101:in `block (2 levels) in top_level'
/home/nies/.rvm/gems/ruby-2.0.0-p353/gems/rake-10.0.3/lib/rake/application.rb:101:in`each'
/home/nies/.rvm/gems/ruby-2.0.0-p353/gems/rake-10.0.3/lib/rake/application.rb:101:in `block in top_level'
/home/nies/.rvm/gems/ruby-2.0.0-p353/gems/rake-10.0.3/lib/rake/application.rb:110:in`run_with_threads'
/home/nies/.rvm/gems/ruby-2.0.0-p353/gems/rake-10.0.3/lib/rake/application.rb:95:in `top_level'
/home/nies/.rvm/gems/ruby-2.0.0-p353/gems/rake-10.0.3/lib/rake/application.rb:73:in`block in run'
/home/nies/.rvm/gems/ruby-2.0.0-p353/gems/rake-10.0.3/lib/rake/application.rb:160:in `standard_exception_handling'
/home/nies/.rvm/gems/ruby-2.0.0-p353/gems/rake-10.0.3/lib/rake/application.rb:70:in`run'
/home/nies/.rvm/gems/ruby-2.0.0-p353/gems/rake-10.0.3/bin/rake:33:in `<top (required)>'
/home/nies/.rvm/gems/ruby-2.0.0-p353/bin/rake:23:in`load'
/home/nies/.rvm/gems/ruby-2.0.0-p353/bin/rake:23:in `<main>'
/home/nies/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in`eval'
/home/nies/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => db:seed

**Comment by jasonblanchard** [comment]
I think that's because you need to copy config/application.yml.example to config/application.yml. I don't think you have to change any values, but when we have API keys and such, that's where they will go.

I'll update the README to include this step.

**Comment by christophernies** [comment]
This was the correct resolution to this issue. Thanks for adding it to the docs, Jason.
